ml:
  # embedding_run_path: models/embeddings/dd5c60e10afe7b51
  # embedding_run_path: models/embeddings/7e59a2c67cab1cde
  
  embedding_run_path: models/embeddings/c63028fbbd858f3c
  output_dir: models/ml_models
  random_state: 42
  force_rerun: false
  hyperparameter_optimization: [false, 10] # true enables Optuna and 10 is the number of trials

  embedding_types:
    - bert_base_uncased
    - bert_large_uncased
    - qwen3_embedding_0_6b
    - bge_base_en_v1_5
    - bge_small_en_v1_5
    - all_minilm_l6_v2
    - bge_m3
    - all_minilm_l12_v2
    - gte_base
    - gte_small
    - gte_large

  types:
    - logistic_regression
    - svm
    - random_forest
    - xgboost
    - decision_tree

  classifiers:
    logistic_regression:
      type: logistic_regression
      max_iter: 1000
      c: 1.0
      solver: lbfgs
      multi_class: auto

    svm:
      type: svm
      kernel: rbf
      c: 1.0
      gamma: scale
      probability: false

    random_forest:
      type: random_forest
      n_estimators: 300
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1

    xgboost:
      type: xgboost
      n_estimators: 300
      max_depth: 6
      learning_rate: 0.1
      subsample: 1.0
      colsample_bytree: 1.0
      reg_alpha: 0.0
      reg_lambda: 1.0

    decision_tree:
      type: decision_tree
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1

